---
- include: compat.yml

- include: include_vars.yml

# Install EPEL
- include: t_epel.yml
  when: ansible_distribution == 'CentOS'

- include: t_Debian.yml
  when: ansible_os_family == 'Debian'

- include: t_RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: install_package_names.yml

# tasks file for isindir.httpd_example
#- name: ensure apache is at the latest version
#  yum: name=httpd state=latest
